# Generated by Django 5.2.1 on 2025-05-28 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentmodel',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('intiger_field', models.IntegerField()),
                ('address', models.TextField(blank=True)),
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('Boolean_field', models.BooleanField(default=False)),
                ('date_field', models.DateField(default=datetime.datetime.today)),
                ('DateTimeField', models.DateTimeField(default=datetime.datetime.now)),
                ('DecimalField', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('duration_field', models.DurationField(blank=True, null=True)),
                ('Email', models.EmailField(default='example@gmail.com', max_length=254, verbose_name='Enter your email address ')),
                ('file_field', models.FileField(upload_to='upload_files/')),
                ('Choose_a_fiel_file_path_field', models.FilePathField(path='media/')),
                ('float_field', models.FloatField(default=0.0)),
                ('GeniricIPAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('image_field', models.ImageField(blank=True, null=True, upload_to='Uploaded_image/')),
                ('json_field', models.JSONField(blank=True, null=True)),
                ('BIO', models.TextField()),
                ('positive_integer_field', models.PositiveIntegerField(default=0)),
                ('big_positive_integerField', models.PositiveBigIntegerField(default=0)),
                ('positive_small_integer', models.PositiveSmallIntegerField(default=0)),
                ('store_urls', models.SlugField(blank=True, unique=True)),
                ('small_integer_field', models.SmallIntegerField()),
                ('time_field', models.TimeField()),
                ('url_field', models.URLField(default='youtube.com')),
                ('UUID_field', models.UUIDField()),
            ],
        ),
    ]
